### ISSUE TITLE
There isn't any tutorial or guide

### ISSUE THREAD

**Issue by manuelp** [elight/coulda#2]
I'm a newbie of BDD and it would be great to read a tutorial on how to use it. Even a very simple program would be ok.

Looking at the example, I don't know how to verify the expectations...

**Comment by elight** [comment]
For starters, you should take a look a Test::Unit.  It comes built into Ruby.  Look in lib/test/unit.

I started today on a static site to provide a tutorial to using Coulda.

**Comment by manuelp** [comment]
I've already used Test::Unit, minitest and shoulda. I think coulda... could be the next step.

OK, found your tutorial [here](http://coulda.tiggerpalace.com/). I'll work with it and tell you how it's going.

Thank you!
